from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib import colors
import os

class pdf_generator:
    """PDF generator using ReportLab to export structural calculation docs."""
    
    @staticmethod
    def generate_project_report(project_data: dict, output_path: str):
        """Generates a multi-page PDF summary of the project and passes."""
        c = canvas.Canvas(output_path, pagesize=A4)
        width, height = A4
        
        # Title Page
        c.setFont("Helvetica-Bold", 24)
        c.drawString(50, height - 100, "Structural Design Report")
        
        c.setFont("Helvetica", 14)
        c.drawString(50, height - 150, f"Project: {project_data.get('name', 'Untitled')}")
        c.drawString(50, height - 180, f"Design Code: {project_data.get('code', 'BNBC 2020')}")
        
        c.setFont("Helvetica", 12)
        c.drawString(50, height - 250, "Generated by DesignBook - AntiGravity App")
        
        c.showPage() # Create new page for content
        
        # Content Page - Bill of Quantities Stub
        c.setFont("Helvetica-Bold", 16)
        c.drawString(50, height - 50, "Bill of Quantities (Estimated)")
        
        c.setFont("Helvetica", 12)
        c.drawString(50, height - 100, f"Total Concrete Volume: {project_data.get('concrete_vol', 0):.2f} m3")
        c.drawString(50, height - 130, f"Total Steel Weight: {project_data.get('steel_weight', 0):.2f} kg")
        c.drawString(50, height - 160, f"Overall Cost Estimate: BDT {project_data.get('total_cost', 0):,.2f}")
        
        c.save()
        
        return output_path
